### ISSUE TITLE
"Dismiss All" does not work

### ISSUE THREAD

**Issue by dlmr** [iamdustan/yellowbox-react#2]
It seems like the `Dismiss All` button does not work. Nothing happens after pressing it, the `Dismiss` button however works fine.

I have not investigated this further at this time.

**Comment by iamdustan** [comment]
all browsers or a specific browser?
react version in use?

I’ll look into it next week.

**Comment by dlmr** [comment]
Sorry for late reply. It was observed on Chrome (not tested others) and React 0.14.3.
